version: '3'
networks:
  default:
    external:
      name: localdev_default
services:
  inventory:
    image: inventory-service
    container_name: inventory-service
    hostname: inventory-service
    ports:
      - 127.0.0.1:8085:8080
    environment:
      - SPRING_PROFILES_ACTIVE=localdev
