apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  labels:
    app: shipping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
        - name: shipping-service
          image: shipping-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: localdev
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  labels:
    app: shipping-service
spec:
  selector:
    app: shipping-service
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: shipping-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/rewrites: "serviceName=shipping-service rewrite=/shippers/"
spec:
  rules:
    - host: kubernetes.docker.internal
      http:
        paths:
          - path: /shippers/
            backend:
              serviceName: shipping-service
              servicePort: http
